/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lecture12;

public class Calculator {

		/**
		 * Multiply 2 floats together.
		 * @param a first factor
		 * @param b second factor
		 * @return the product of a and b
		 */ 
		public float multiply(float a, float b) {
				return a * b;
		}

		/**
		 * Divide 2 floats.
		 * @param a dividend
		 * @param b divisor
		 * @return the quotient of a and b
		 * @deprecated
		 */
		public float divide(float a, float b) {
		    return a / b;
		}

		/**
		 * Safely divide 2 floats. The epsilon parameter is used
		 * as a replacement for the divisor when the divisor is 0.
		 * @param a dividend
		 * @param b divisor
		 * @param e epsilon 
		 * @return the quotient of a and b
		 */
		public float divide(float a, float b, float e) {
		    return b == 0 ? a/e : a/b;
		}

		/**
		 * Get a String that represents the provided formula.
		 * @param a first variable
		 * @param b second variable
		 * @param op operator (multiply or divide)
		 * @return representation of the formula
		 * @see printMath
		 */
    public String mathString(float a, float b, String op){
				return op == "multiply" ? (a + "*" + b) : (a + "/" + b); 
    }

		/**
		 * Print a String that represents the provided formula.
		 * @param a first variable
		 * @param b second variable
		 * @param op operator (multiply or divide)
		 * @see mathString
		 */
		public void printMath(float a, float b, String op) {
				System.out.println(mathString(a, b, op));
		}
}
