/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lecture12;

import org.junit.Test;
import static org.junit.Assert.*;

public class CalculatorTest {

		@Test public void multiply() {
		    Calculator calc = new Calculator();
				assertEquals(2, calc.multiply(1, 2), 0.01);
		}

		@Test public void divide() {
		    Calculator calc = new Calculator();
				assertEquals(0.5, calc.divide(1, 2), 0.01);
		}

		@Test public void safe_divide() {
		    Calculator calc = new Calculator();
				assertEquals(200, calc.divide(2, 0, 0.01f), 0.01);
		}

		@Test public void mathString() {
		    Calculator calc = new Calculator();
				assertEquals("1.0*2.0", calc.mathString(1,2,"multiply"));
		}
}
